# 测试配置文件 - 包含错误配置
global:
  nginx_config_dir: "/Users/limingze/docker/nginx-ui/nginx/sites-available"
  stream_config_dir: "/Users/limingze/docker/nginx-ui/nginx/streams-available"
  nginx_reload_cmd: "docker exec nginx-ui nginx -s reload"
  
  # 默认代理配置
  default_proxy:
    client_max_body_size: "2048M"
    proxy_http_version: "1.1"
    proxy_headers:
      - "Upgrade $http_upgrade"
      - "Connection upgrade"
      - "X-Real-IP $remote_addr"
      - "X-Forwarded-For $proxy_add_x_forwarded_for"
      - "X-Forwarded-Proto $scheme"
      - "X-Forwarded-Host $http_host"
    proxy_redirect: "off"

# 服务配置
services:
  # 正确的配置
  - name: "portainer"
    type: "http"
    container_name: "portainer"
    domain: "portainer.ybdx.xyz"
    path: "/"
    port: 9000
    upstream_name: "portainer"
    
  # 错误的配置 - 容器名称不存在
  - name: "nonexistent-service"
    type: "http"
    container_name: "nonexistent-container"
    domain: "nonexistent.example.com"
    path: "/"
    port: 8080
    upstream_name: "nonexistent_backend"
    
  # 错误的配置 - 缺少必要字段
  - name: "invalid-service"
    type: "http"
    container_name: "nginx-ui"
    # domain: "missing-domain"  # 缺少domain字段
    path: "/"
    port: 8000
    upstream_name: "invalid_backend"
